# Generated by Django 3.2.5 on 2022-05-29 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databaseapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='keydatabase',
            name='id',
        ),
        migrations.AlterField(
            model_name='keydatabase',
            name='keys',
            field=models.CharField(max_length=500, primary_key=True, serialize=False),
        ),
    ]
