# Generated by Django 3.2.5 on 2022-05-29 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databaseapp', '0002_auto_20220529_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keydatabase',
            name='keys',
            field=models.CharField(max_length=500, primary_key=True, serialize=False, unique=True),
        ),
    ]
