# Generated by Django 3.2.5 on 2022-05-30 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databaseapp', '0003_alter_keydatabase_keys'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keydatabase',
            name='keys',
            field=models.CharField(max_length=500, primary_key=True, serialize=False),
        ),
    ]
